version: "3.9"

services:
  rds:
    container_name: postgresql
    image: postgres:latest
    env_file:
      - configurations/.env.staging
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - redisconfig:/etc/redis
    restart: on-failure

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    env_file:
      - configurations/.env.staging
    volumes:
      - influxdata:/var/lib/influxdb
    restart: on-failure

  api:
    container_name: http-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /server
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - configurations/.env.staging
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis
      - influxdb
      - rds

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - configurations/.env.staging
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: on-failure
    depends_on:
      - api

  queue:
    container_name: queue
    build: ./queue
    user: nobody
    env_file:
      - configurations/.env.staging
    depends_on:
      - api
      - influxdb
      - rabbitmq
    restart: on-failure

volumes:
  pgdata:
  redisdata:
  redisconfig:
  influxdata:
  rabbitmqdata:
